export const FETCH_PAST_LAUNCHES_REQUEST = 'FETCH_PAST_LAUNCHES_REQUEST'
export const FETCH_PAST_LAUNCHES_SUCCESS = 'FETCH_PAST_LAUNCHES_SUCCESS'
export const FETCH_PAST_LAUNCHES_FAILURE = 'FETCH_PAST_LAUNCHES_FAILURE'
